query ($search: String, $page: Int, $perPage: Int) {
    Page(page: $page, perPage: $perPage) {
        media (search: $search) {
        	id
        	season
      		format
      		status
      		genres
            isAdult
      		volumes
      		duration
      		episodes
      		chapters
      		popularity
      		averageScore
            coverImage {
                large
                medium
            }
        	title {
                native
                romaji
                english
        	}
      		startDate {
                day
                year
                month
      		}
            endDate {
                day
                year
                month
            }
        }
  	}
}