query ($search: String, $page: Int, $perPage: Int) {
    Page(page: $page, perPage: $perPage) {
        media (search: $search) {
        	id
        	season
      		format
      		status
      		genres
            source
      		volumes
            isAdult
            siteUrl
      		duration
      		episodes
      		chapters
            description
            bannerImage
      		averageScore
            countryOfOrigin
            trailer {
                id
                site
            }            
            coverImage {
                large
                medium
            }
      		externalLinks {
      		    id
                url
      		}
            nextAiringEpisode {
      		    id
                timeUntilAiring
      		}
      		rankings {
                id
                rank
                type
      		}
      		startDate {
                day
                year
                month
      		}
            endDate {
                day
                year
                month
            }
        	title {
                native
                romaji
                english
        	}
        }
  	}
}
