query ($search: String, $page: Int, $perPage: Int) {
    Page(page: $page, perPage: $perPage) {
        media (search: $search) {
        	id
        	season
            isAdult
            coverImage {
                large
                medium
            }
        	title {
                romaji
                english
                native
        	}
        }
  	}
}